import React, { useState } from "react";
import { createRoot } from "react-dom/client";
import { Lock, Droplets, Building2, Radio, Smartphone, Coins, Users, Briefcase, BarChart3, Globe2, ArrowRight, X } from "lucide-react";
import { motion, AnimatePresence } from "framer-motion";
import "./index.css";

const revenueItems = [
  { name: "Subscription", icon: Users, margin: "High-margin recurring revenue", example: "Monthly access for hotels, operators, communities, and enterprise partners.", potential: "$25–$250 per user or account per month depending on access tier." },
  { name: "Licensing", icon: Briefcase, margin: "Strong margin with low delivery cost after setup", example: "Territory operator licenses and enterprise white-label deployments.", potential: "Setup fees, annual license fees, and revenue share." },
  { name: "Events", icon: Radio, margin: "Variable margin tied to attendance and sponsorship", example: "Hotel watch parties, sports activations, branded experiences, and live events.", potential: "Ticketing, vendor fees, sponsorship, food and beverage, and media monetization." },
  { name: "Telecom", icon: Globe2, margin: "Partner-driven recurring margin", example: "Connectivity, device bundles, hospitality Wi-Fi, and telecom partner channels.", potential: "Commission, recurring carrier revenue, and enterprise service fees." },
  { name: "Beverage", icon: Droplets, margin: "Product margin plus brand sponsorship value", example: "VIBE Water powered by Hello Energy and embedded into events and hotel activations.", potential: "Case sales, venue distribution, sponsor placements, and private-label expansion." },
  { name: "Token", icon: Coins, margin: "Network upside if structured compliantly", example: "Wallet rewards, loyalty, digital access, and transaction incentives.", potential: "Utility-driven engagement, partner rewards, and ecosystem transaction activity." },
  { name: "Consulting", icon: BarChart3, margin: "High-margin advisory and implementation fees", example: "Enterprise launch support, AI workflows, community activations, and operator training.", potential: "$5,000–$100,000+ per engagement depending on scope." },
  { name: "Equity", icon: Building2, margin: "Long-term upside", example: "SPV participation, territory entities, preferred shares, and strategic ownership.", potential: "Appreciation, dividends, exits, and structured buyback rights." }
];

function Button({ children, onClick, variant = "primary", type = "button" }) {
  const base = "inline-flex items-center justify-center gap-2 rounded-2xl px-5 py-3 font-semibold transition active:scale-[0.98]";
  const styles = variant === "secondary" ? "border border-white/20 bg-white/10 text-white hover:bg-white/15" : "bg-white text-black hover:bg-zinc-200";
  return <button type={type} onClick={onClick} className={`${base} ${styles}`}>{children}</button>;
}

function Section({ id, eyebrow, title, children }) {
  return <section id={id} className="px-6 py-20 md:px-12"><div className="mx-auto max-w-6xl">{eyebrow && <p className="mb-3 text-sm font-semibold uppercase tracking-[0.3em] text-cyan-300">{eyebrow}</p>}<h2 className="mb-6 text-3xl font-bold md:text-5xl">{title}</h2>{children}</div></section>;
}

function Landing({ goDeal, goOperator }) {
  const [selected, setSelected] = useState(null);
  return <div className="min-h-screen bg-black text-white">
    <nav className="sticky top-0 z-40 border-b border-white/10 bg-black/80 px-6 py-4 backdrop-blur md:px-12"><div className="mx-auto flex max-w-6xl items-center justify-between"><div className="text-lg font-black tracking-[0.25em]">VIBE100</div><div className="hidden gap-6 text-sm text-zinc-300 md:flex"><a href="#ecosystem">Ecosystem</a><a href="#revenue">Revenue</a><a href="#htes">HTES</a><a href="#water">Water</a></div><Button onClick={goDeal}>Deal Room <Lock size={16}/></Button></div></nav>
    <section className="relative flex min-h-screen items-center justify-center overflow-hidden px-6 text-center"><div className="absolute inset-0 bg-[radial-gradient(circle_at_top,rgba(34,211,238,0.2),transparent_35%),radial-gradient(circle_at_bottom,rgba(99,102,241,0.18),transparent_35%)]"/><motion.div initial={{opacity:0,y:24}} animate={{opacity:1,y:0}} className="relative z-10 max-w-4xl"><p className="mb-5 text-sm font-semibold uppercase tracking-[0.35em] text-cyan-300">VIBE Enterprises</p><h1 className="mb-6 text-5xl font-black leading-tight md:text-7xl">We Control Distribution. We Monetize Everything.</h1><p className="mx-auto mb-8 max-w-2xl text-xl text-zinc-300">Consumer distribution. Enterprise monetization. Infinite scale across hotels, events, telecom, beverage, devices, and token-enabled commerce.</p><div className="flex flex-col justify-center gap-4 sm:flex-row"><Button onClick={goDeal}>Enter Deal Room <ArrowRight size={18}/></Button><Button onClick={goOperator} variant="secondary">Become Operator</Button></div></motion.div></section>
    <Section id="ecosystem" eyebrow="Ecosystem" title="One network. Multiple monetization layers."><div className="grid gap-5 md:grid-cols-3">{["True Perspective Global","VIBE Enterprises","VIBE Network"].map((item,i)=><div key={item} className="rounded-3xl border border-white/10 bg-white/[0.04] p-6 shadow-2xl"><div className="mb-4 flex h-12 w-12 items-center justify-center rounded-2xl bg-white text-black">{i+1}</div><h3 className="mb-3 text-2xl font-bold">{item}</h3><p className="text-zinc-300">{i===0&&"Strategic infrastructure, relationships, and enterprise-level business development."}{i===1&&"Licensing, monetization, SPV coordination, and revenue architecture."}{i===2&&"Execution layer for hotels, events, operators, products, devices, and community distribution."}</p></div>)}</div></Section>
    <Section id="revenue" eyebrow="Revenue Engine" title="Clickable revenue grid"><div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-4">{revenueItems.map((item)=>{const Icon=item.icon;return <button key={item.name} onClick={()=>setSelected(item)} className="rounded-3xl border border-white/10 bg-white/[0.04] p-6 text-left hover:bg-white/[0.08]"><Icon className="mb-4 text-cyan-300"/><h3 className="text-xl font-bold">{item.name}</h3><p className="mt-2 text-sm text-zinc-400">View margin, example deal, and revenue potential.</p></button>})}</div></Section>
    <Section id="htes" eyebrow="Front Door Recommendation" title="Start with HTES + VIBE Water + Events"><div className="grid gap-6 md:grid-cols-3"><div className="rounded-3xl bg-white p-6 text-black"><h3 className="text-2xl font-bold">Hotels</h3><p className="mt-3">100+ property pipeline strategy with repeatable activation packages.</p></div><div className="rounded-3xl border border-white/10 bg-white/[0.04] p-6"><h3 className="text-2xl font-bold">Events</h3><p className="mt-3 text-zinc-300">Watch parties, sports moments, local promotions, and sponsor integration.</p></div><div className="rounded-3xl border border-white/10 bg-white/[0.04] p-6"><h3 className="text-2xl font-bold">Fast Revenue</h3><p className="mt-3 text-zinc-300">Easier to explain, easier to sell, and visible immediately.</p></div></div></Section>
    <Section id="water" eyebrow="VIBE Water" title="Private-label beverage built into distribution."><div className="rounded-3xl border border-cyan-300/30 bg-cyan-300/10 p-8"><p className="text-xl text-zinc-100">Powered by Hello Energy manufacturing, VIBE Water becomes an embedded product layer across hotel activations, event sponsorships, operator territories, and branded experiences.</p><div className="mt-8 grid gap-4 md:grid-cols-3"><div className="rounded-2xl bg-black/40 p-5"><b>Unit Economics</b><p className="mt-2 text-zinc-300">Case sales and private-label margins.</p></div><div className="rounded-2xl bg-black/40 p-5"><b>Distribution</b><p className="mt-2 text-zinc-300">Hotels, venues, events, and operators.</p></div><div className="rounded-2xl bg-black/40 p-5"><b>Sponsorship</b><p className="mt-2 text-zinc-300">Brand placements and bundled activation value.</p></div></div></div></Section>
    <Section id="device" eyebrow="Device + Token Layer" title="$30 device → $300–$800 lifetime value target"><div className="flex flex-col gap-6 rounded-3xl border border-white/10 bg-white/[0.04] p-8 md:flex-row md:items-center md:justify-between"><div><h3 className="text-2xl font-bold">Wallet + token integration</h3><p className="mt-3 max-w-3xl text-zinc-300">Devices and wallets can be layered after the faster HTES + Water + Events model proves distribution and monetization.</p></div><Smartphone size={72} className="text-cyan-300"/></div></Section>
    <section className="px-6 py-20 text-center md:px-12"><h2 className="mb-6 text-4xl font-bold">Join the Network</h2><div className="flex flex-col justify-center gap-4 sm:flex-row"><Button onClick={goDeal}>Request Investor Access</Button><Button onClick={goOperator} variant="secondary">Apply as Operator</Button></div></section>
    <AnimatePresence>{selected&&<motion.div initial={{opacity:0}} animate={{opacity:1}} exit={{opacity:0}} className="fixed inset-0 z-50 flex items-center justify-center bg-black/80 p-6 backdrop-blur"><motion.div initial={{scale:.96,y:20}} animate={{scale:1,y:0}} exit={{scale:.96,y:20}} className="w-full max-w-xl rounded-3xl border border-white/10 bg-zinc-950 p-6 shadow-2xl"><div className="mb-5 flex items-start justify-between gap-4"><div><p className="text-sm uppercase tracking-[0.25em] text-cyan-300">Revenue Layer</p><h3 className="mt-2 text-3xl font-bold">{selected.name}</h3></div><button onClick={()=>setSelected(null)} className="rounded-full bg-white/10 p-2 hover:bg-white/20"><X size={20}/></button></div><div className="space-y-4 text-zinc-300"><p><b className="text-white">Margin profile:</b> {selected.margin}</p><p><b className="text-white">Example deal:</b> {selected.example}</p><p><b className="text-white">Revenue potential:</b> {selected.potential}</p></div></motion.div></motion.div>}</AnimatePresence>
  </div>;
}

function DealRoomGate({ onSuccess, goHome }) { const [code,setCode]=useState(""); const [error,setError]=useState(""); const handleAccess=()=>{ if(code.trim().toUpperCase()==="VIBE100") onSuccess(); else setError("Access denied. Use VIBE100 for this preview.");}; return <div className="flex min-h-screen items-center justify-center bg-black px-6 text-white"><div className="w-full max-w-md rounded-3xl border border-white/10 bg-white/[0.04] p-8 text-center shadow-2xl"><div className="mx-auto mb-5 flex h-16 w-16 items-center justify-center rounded-3xl bg-white text-black"><Lock/></div><h1 className="mb-3 text-3xl font-bold">Enter Deal Room</h1><p className="mb-6 text-zinc-400">Private investor access for overview, live deals, financials, and allocation.</p><input value={code} onChange={(e)=>setCode(e.target.value)} onKeyDown={(e)=>e.key==="Enter"&&handleAccess()} placeholder="Access Code" className="mb-3 w-full rounded-2xl border border-white/10 bg-black p-3 text-white outline-none focus:border-cyan-300"/>{error&&<p className="mb-3 text-sm text-red-300">{error}</p>}<div className="flex gap-3"><Button onClick={handleAccess}>Enter</Button><Button onClick={goHome} variant="secondary">Back</Button></div></div></div>;}
function DealRoom({ goOperator, goHome }) { const cards=[["Overview","VIBE Enterprises operates as the licensing and monetization hub for distribution-first revenue."],["Live Deals","HTES hotel activations, VIBE Water placements, operator territories, and strategic partner targets."],["Financials","3-year projections, unit economics, revenue share models, and SPV economics."],["Allocation","Investor access, preferred share pools, operator participation, and availability tracking."]]; return <div className="min-h-screen bg-black px-6 py-10 text-white md:px-12"><div className="mx-auto max-w-6xl"><div className="mb-10 flex flex-col justify-between gap-4 md:flex-row md:items-center"><div><p className="text-sm uppercase tracking-[0.3em] text-cyan-300">Private Side</p><h1 className="mt-2 text-4xl font-black md:text-6xl">VIBE Deal Room</h1></div><div className="flex gap-3"><Button onClick={goOperator}>Operator Form</Button><Button onClick={goHome} variant="secondary">Public Site</Button></div></div><div className="grid gap-5 md:grid-cols-2">{cards.map(([title,body])=><div key={title} className="rounded-3xl border border-white/10 bg-white/[0.04] p-7"><h2 className="mb-3 text-2xl font-bold">{title}</h2><p className="text-zinc-300">{body}</p></div>)}</div><div className="mt-8 rounded-3xl bg-white p-7 text-black"><h2 className="text-2xl font-bold">Investor Data Room Structure</h2><div className="mt-5 grid gap-4 md:grid-cols-3">{["Corporate Structure","Financials","Licensing Framework","Go-To-Market","Product + Distribution","Token + Tech","Pipeline"].map(folder=><div key={folder} className="rounded-2xl border border-black/10 p-4 font-semibold">📁 {folder}</div>)}</div></div></div></div>;}
function OperatorForm({ goHome }) { const [submitted,setSubmitted]=useState(false); if(submitted) return <div className="flex min-h-screen items-center justify-center bg-black px-6 text-white"><div className="max-w-xl rounded-3xl border border-white/10 bg-white/[0.04] p-8 text-center"><h1 className="mb-3 text-3xl font-bold">Operator Application Received</h1><p className="mb-6 text-zinc-300">This preview can later connect to Google Sheets, Airtable, HubSpot, Klaviyo, Make, or a full backend database.</p><Button onClick={goHome}>Return Home</Button></div></div>; return <div className="min-h-screen bg-black px-6 py-12 text-white md:px-12"><div className="mx-auto grid max-w-6xl gap-8 md:grid-cols-2"><div><p className="text-sm uppercase tracking-[0.3em] text-cyan-300">Operator Page</p><h1 className="mt-3 text-4xl font-black md:text-6xl">Become a VIBE Operator</h1><p className="mt-5 text-lg text-zinc-300">Apply for territory rights, HTES activation channels, VIBE product distribution, and performance-based expansion opportunities.</p><div className="mt-8 rounded-3xl border border-white/10 bg-white/[0.04] p-6"><h2 className="mb-4 text-2xl font-bold">Compensation Framework</h2><ul className="space-y-3 text-zinc-300"><li>• 10–30% revenue share potential</li><li>• License and setup fee structure</li><li>• Territory exclusivity based on performance</li><li>• Equity eligibility through territory entity or SPV pool</li></ul></div></div><form onSubmit={(e)=>{e.preventDefault();setSubmitted(true);}} className="rounded-3xl border border-white/10 bg-white/[0.04] p-6 shadow-2xl"><div className="grid gap-4">{["Name","Email","Phone","Territory","Experience","Capital Capacity"].map(field=><input key={field} placeholder={field} className="rounded-2xl border border-white/10 bg-black p-3 text-white outline-none focus:border-cyan-300"/>)}<textarea placeholder="Tell us why you are a strong territory operator" className="min-h-32 rounded-2xl border border-white/10 bg-black p-3 text-white outline-none focus:border-cyan-300"/><Button type="submit">Apply</Button><Button onClick={goHome} variant="secondary">Back to Public Site</Button></div></form></div></div>;}
function App(){ const [stage,setStage]=useState("landing"); if(stage==="gate") return <DealRoomGate onSuccess={()=>setStage("deal")} goHome={()=>setStage("landing")}/>; if(stage==="deal") return <DealRoom goOperator={()=>setStage("operator")} goHome={()=>setStage("landing")}/>; if(stage==="operator") return <OperatorForm goHome={()=>setStage("landing")}/>; return <Landing goDeal={()=>setStage("gate")} goOperator={()=>setStage("operator")}/>; }

createRoot(document.getElementById("root")).render(<App />);
